/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author vanes
 */
public class Confirmacion extends javax.swing.JFrame {

    /**
     * Creates new form Confirmacion
     */
    ArrayList<Solicitud> solicitudes;
    ArrayList<Aprobados> aprobados;
    int pos;

    public Confirmacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        lblnombre.setVisible(false);
        lblpass.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jSeparator1.setVisible(false);
    }

    public Confirmacion(ArrayList<Solicitud> solicitudes, ArrayList<Aprobados> aprobados) {
        initComponents();
        this.solicitudes = solicitudes;
        this.aprobados = aprobados;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        lblnombre.setVisible(false);
        lblpass.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jSeparator1.setVisible(false);

        for (Solicitud sol : solicitudes) {
            combo.addItem(sol.getNombre());
        }

    }

    public void Seleccionar(String nombre) {
        for (Solicitud sol : solicitudes) {
            if (sol.getNombre().equalsIgnoreCase(nombre)) {
                lblnombre.setText(nombre);
                lblpass.setText(sol.getPassword());
                return;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblnombre = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Solicitudes de usuarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Usuario que envió la solicitud");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        combo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 190, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Nombre de usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Contraseña del usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 200, 10));

        lblnombre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(0, 0, 0));
        lblnombre.setText("jLabel5");
        jPanel1.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        lblpass.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblpass.setForeground(new java.awt.Color(0, 0, 0));
        lblpass.setText("jLabel6");
        jPanel1.add(lblpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Enter_ON.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 120, 40));

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Button-Ok-icon.png"))); // NOI18N
        jButton2.setText("Aceptar solicitud");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 230, 70));

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_Multiply_32px.png"))); // NOI18N
        jButton3.setText("Denegar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 220, 70));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_Back_64px.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        this.dispose();
        Administrador admin = new Administrador(solicitudes, aprobados);
        admin.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pos = obtener();

    }//GEN-LAST:event_jButton1ActionPerformed
    private int obtener() {
        if (combo.getSelectedIndex() != 0) {
            Seleccionar(combo.getSelectedItem().toString());
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            lblnombre.setVisible(true);
            lblpass.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jSeparator1.setVisible(true);
            return combo.getSelectedIndex();
        }
        return 0;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        aprobados.add(new Aprobados(lblnombre.getText(), lblpass.getText(), new Estado("00:00","0","0")));
        JOptionPane.showMessageDialog(null, "¡Se ha aprobado la solicitud!");
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        lblnombre.setVisible(false);
        lblpass.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jSeparator1.setVisible(false);
        if (pos != 0) {
            solicitudes.remove(pos - 1);
        }
        combo.removeAllItems();
        combo.addItem("Seleccionar");
        for (Solicitud sol : solicitudes) {
            combo.addItem(sol.getNombre());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (pos != 0) {
            solicitudes.remove(pos - 1);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            lblnombre.setVisible(false);
            lblpass.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jSeparator1.setVisible(false);
            JOptionPane.showMessageDialog(null, "¡Solicitud rechazada!");
            combo.removeAllItems();
            combo.addItem("Seleccionar");
            for (Solicitud sol : solicitudes) {
                combo.addItem(sol.getNombre());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirmacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblpass;
    // End of variables declaration//GEN-END:variables
}
